name: Docker Image CI

on:
    push: 
      branches: [main]
    pull_request:
      branches: [main]

jobs:
  forces:
    runs-on: ubuntu-latest
    container:
      image: fluidattacks/forces:latest
      env:
        ftoken: ${{ secrets.FTOKEN }}
    steps:
      - name: Run Agent check
        run: forces --token ${FTOKEN} --strict --breaking 4.0
